name: kve-lhc
summary: Hello world application for LHC
description: |
  Cpitao Caveeeeerna
grade: stable
confinement: strict

apps:
  kve-lhc:
    command: bin/hello-lhc

parts:
  simple:
    plugin: make
    source: .
